#!/bin/sh

[ -f /etc/config/firewall ] || return 0 2>/dev/null || exit 0

uci -q batch << 'EOF'
	delete firewall.allow_ssh_wan
	set firewall.allow_ssh_wan=rule
	set firewall.allow_ssh_wan.name='Allow-SSH-WAN'
	set firewall.allow_ssh_wan.src='wan'
	set firewall.allow_ssh_wan.proto='tcp'
	set firewall.allow_ssh_wan.dest_port='22'
	set firewall.allow_ssh_wan.target='ACCEPT'

	delete firewall.allow_http_wan
	set firewall.allow_http_wan=rule
	set firewall.allow_http_wan.name='Allow-HTTP-WAN'
	set firewall.allow_http_wan.src='wan'
	set firewall.allow_http_wan.proto='tcp'
	set firewall.allow_http_wan.dest_port='80'
	set firewall.allow_http_wan.target='ACCEPT'

	delete firewall.allow_https_wan
	set firewall.allow_https_wan=rule
	set firewall.allow_https_wan.name='Allow-HTTPS-WAN'
	set firewall.allow_https_wan.src='wan'
	set firewall.allow_https_wan.proto='tcp'
	set firewall.allow_https_wan.dest_port='443'
	set firewall.allow_https_wan.target='ACCEPT'

	delete firewall.allow_iperf3_wan
	set firewall.allow_iperf3_wan=rule
	set firewall.allow_iperf3_wan.name='Allow-IPERF3-WAN'
	set firewall.allow_iperf3_wan.src='wan'
	set firewall.allow_iperf3_wan.proto='tcp udp'
	set firewall.allow_iperf3_wan.dest_port='5201'
	set firewall.allow_iperf3_wan.target='ACCEPT'

	commit firewall
EOF

return 0 2>/dev/null || exit 0
